name: bch709_vibe_coding
channels:
  - conda-forge
  - bioconda
  - defaults
  - nodefaults
dependencies:
  - _openmp_mutex=4.5=20_gnu
  - _r-mutex=1.0.1=anacondar_1
  - alsa-lib=1.2.15.3=hb03c661_0
  - binutils_impl_linux-64=2.45.1=default_hfdba357_101
  - biopython=1.86=py311h49ec1c0_1
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - bwidget=1.10.1=ha770c72_1
  - bzip2=1.0.8=hda65f42_9
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - contourpy=1.3.3=py311h724c32c_4
  - curl=8.18.0=h4e3cde8_0
  - cycler=0.12.1=pyhcf101f3_2
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dbus=1.16.2=h24cb091_1
  - double-conversion=3.4.0=hecca717_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.17.1=h27c8c51_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py311h3778330_0
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - gcc_impl_linux-64=15.2.0=he420e7e_18
  - gfortran_impl_linux-64=15.2.0=h281d09f_18
  - graphite2=1.3.14=hecca717_2
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=15.2.0=hda75c37_18
  - harfbuzz=12.2.0=h15599e2_0
  - icu=75.1=he02047a_0
  - kernel-headers_linux-64=6.12.0=he073ed8_5
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py311h724c32c_2
  - krb5=1.21.3=h659f571_0
  - lcms2=2.18=h0c24ade_0
  - ld_impl_linux-64=2.45.1=default_hbd61a6d_101
  - lerc=4.0.0=h0aef613_1
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcblas=3.11.0=5_h0358290_openblas
  - libclang-cpp21.1=21.1.8=default_h99862b1_3
  - libclang13=21.1.8=default_h746c552_3
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.18.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.7.4=hecca717_0
  - libffi=3.5.2=h3435931_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_18
  - libgcc-devel_linux-64=15.2.0=hcc6f6b0_118
  - libgcc-ng=15.2.0=h69a702a_18
  - libgfortran=15.2.0=h69a702a_18
  - libgfortran-ng=15.2.0=h69a702a_18
  - libgfortran5=15.2.0=h68bc16d_18
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.4=h6548e54_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=he0feb66_18
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=5_h47877c9_openblas
  - libllvm21=21.1.8=hf7376ad_0
  - liblzma=5.8.2=hb03c661_0
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopengl=1.7.0=ha4b6fd6_2
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.55=h421ea60_0
  - libpq=18.1=h5c52fec_2
  - libsanitizer=15.2.0=h90f66d4_18
  - libsqlite=3.51.2=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_18
  - libstdcxx-devel_linux-64=15.2.0=hd446a21_118
  - libstdcxx-ng=15.2.0=hdf11a46_18
  - libtiff=4.7.1=h9d88235_1
  - libuuid=2.41.3=h5347b49_0
  - libvulkan-loader=1.4.341.0=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.13.1=hca5e8e5_0
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libxslt=1.1.43=h711ed8c_1
  - libzlib=1.3.1=hb9d3cd8_2
  - make=4.4.1=hb9d3cd8_2
  - matplotlib=3.10.8=py311h38be061_0
  - matplotlib-base=3.10.8=py311h0f3be63_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - numpy=2.4.2=py311h2e04523_1
  - openjpeg=2.5.4=h55fea9a_0
  - openldap=2.6.10=he970967_0
  - openssl=3.6.1=h35e630c_1
  - packaging=26.0=pyhcf101f3_0
  - pandas=3.0.1=py311h8032f78_0
  - pango=1.56.4=hadf4263_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.47=haa7fec5_0
  - pillow=12.1.1=py311hf88fc01_0
  - pip=26.0.1=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyparsing=3.3.2=pyhcf101f3_0
  - pyside6=6.10.1=py311he4c1a5a_0
  - python=3.11.14=hd63d673_3_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=8_cp311
  - qhull=2020.2=h434a139_5
  - qt6-main=6.10.1=h6f76662_3
  - r-base=4.3.3=hc28aa72_21
  - r-cli=3.6.5=r43h93ab643_0
  - r-colorspace=2.1_1=r43hdb488b9_0
  - r-crayon=1.5.3=r43hc72bb7e_1
  - r-data.table=1.17.8=r43h1c8cec4_0
  - r-ellipsis=0.3.2=r43hb1dbf0f_3
  - r-fansi=1.0.6=r43hb1dbf0f_1
  - r-farver=2.1.2=r43ha18555a_1
  - r-ggplot2=3.5.2=r43hc72bb7e_0
  - r-glue=1.8.0=r43h2b5f3a1_0
  - r-gtable=0.3.6=r43hc72bb7e_0
  - r-isoband=0.2.7=r43ha18555a_3
  - r-labeling=0.4.3=r43hc72bb7e_1
  - r-lattice=0.22_7=r43h2b5f3a1_0
  - r-lifecycle=1.0.4=r43hc72bb7e_1
  - r-magrittr=2.0.3=r43hb1dbf0f_3
  - r-mass=7.3_60.0.1=r43hb1dbf0f_1
  - r-matrix=1.6_5=r43he966344_1
  - r-mgcv=1.9_3=r43h2ae2be5_0
  - r-munsell=0.5.1=r43hc72bb7e_1
  - r-nlme=3.1_168=r43hb67ce94_0
  - r-pheatmap=1.0.13=r43hc72bb7e_0
  - r-pillar=1.11.0=r43hc72bb7e_0
  - r-pkgconfig=2.0.3=r43hc72bb7e_4
  - r-r6=2.6.1=r43hc72bb7e_0
  - r-rcolorbrewer=1.1_3=r43h785f33e_3
  - r-rlang=1.1.6=r43h93ab643_0
  - r-scales=1.4.0=r43hc72bb7e_0
  - r-tibble=3.3.0=r43h2b5f3a1_0
  - r-utf8=1.2.6=r43h2b5f3a1_0
  - r-vctrs=0.6.5=r43h0d4f4ea_1
  - r-viridislite=0.4.2=r43hc72bb7e_2
  - r-withr=3.0.2=r43hc72bb7e_0
  - readline=8.3=h853b02a_0
  - scipy=1.17.1=py311hbe70eeb_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - sed=4.9=h6688a6e_0
  - setuptools=82.0.0=pyh332efcf_0
  - six=1.17.0=pyhe01879c_1
  - statsmodels=0.14.6=py311h0372a8f_0
  - sysroot_linux-64=2.39=hc4b9eeb_5
  - tk=8.6.13=noxft_h366c992_103
  - tktable=2.10=h8d826fa_7
  - tornado=6.5.4=py311h41d9c34_0
  - tqdm=4.67.3=pyh8f84b5b_0
  - tzdata=2025c=hc9c84f9_1
  - unicodedata2=17.0.1=py311h49ec1c0_0
  - wayland=1.24.0=hd6090a7_1
  - wheel=0.46.3=pyhd8ed1ab_0
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.6=hb03c661_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.13=he1eb515_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxcomposite=0.4.7=hb03c661_0
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.7=hb03c661_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.5=hb03c661_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.7=hb03c661_0
  - zlib-ng=2.3.3=hceb46e0_1
  - zstd=1.5.7=hb78ec9c_6
prefix: /home/ryangustafson/miniconda3/envs/bch709_vibe_coding
